### ISSUE TITLE
Node program flow broken after two `close()` call

### ISSUE THREAD

**Issue by huan** [ClickSimply/snap-db#10]
I assume you agree that the snapDb can be closed more than one time because you had merged my unit test for that (allow call `close()` twice).

However, I found when I call the `close` twice, the program flow had been broken.

The following code will demonstrate that, we can expect we get the following output message:

```sh
before close1
before close2
after close 1&2
```

However, what we get will be:

```sh
$ ./t.ts 
before close1
before close2
undefined
```

The re-produceable code:

```ts
#!/usr/bin/env ts-node

import {
  SnapDB,
}               from 'snap-db'

async function main () {
  const db = new SnapDB({
    dir: '/tmp/xx',
    key: 'string',
  })
  console.info('before close1')
  await db.close()
  console.info('before close2')
  await db.close()
  console.info('after close 1&2')
}

main()
  .catch(console.error)
```

**Comment by ClickSimply** [comment]
`1.1.3` has been released on NPM and resolves this issue.  Feel free to comment if you find anything further!

**Comment by huan** [comment]
Nice!
