### ISSUE TITLE
Performance for multiple instances

### ISSUE THREAD

**Issue by nullart2** [ClickSimply/snap-db#15]
Hi,

Should I be concerned of performance if I use multiple instance of snap-db? Basically, I'll treat each instance as a table. Please advise
```
const users = New SnapDB('folder1');
const groups = New SnapDB('folder2);
const news = New SnapDB('folder3');
const blogs = New SnapDB('folder4');
```

**Comment by only-cliches** [comment]
Nah, should be fine.  The bottleneck is almost always javascript, followed by your disk speed.

If you ever need to handle thousands of writes/reads per second you should probably be using LevelDB or RocksDB, I would say this project is only good for smaller, less stressful environments.
