### ISSUE TITLE
What can we expect when we call get with a non-exist key?

### ISSUE THREAD

**Issue by huan** [ClickSimply/snap-db#3]
I found the `snapDb.get('non-exist-key')` will return a string:

> Unable to get key or key not found!

Which is not expected from my code.

I believe it could be better if returns an `undefined`.

I write a unit test for it, and it can not pass with the head of the master branch code.
```ts
        it("Get non-exist key", async (done: MochaDone) => {
            try {
                const val = await db_str.get('non-exist-key')
                console.log('VAL', val)
                expect(val).to.equal(undefined, "get a non-exist key should return undefined");
                done();
            } catch (e) {
                done(e);
            }
        });
```

Could you please explain that what's the expected behavior of the `get` method, and what should I do if I want to know whether my `key` exists in the snapDb?

Thanks!

**Comment by ClickSimply** [comment]
The newest version, `1.1.2` will return `undefined` instead of an error on blank keys.

**Comment by huan** [comment]
Thanks for the fix!

However, I found the current version of the code returns `null` instead of the `undefined`, it's strange, so I send a PR to add a unit test for that.

And also, I believe we should change the return type from  `Promise<string>` to ` Promise<undefined | string>` in `index.ts`:

https://github.com/ClickSimply/snap-db/blob/4358242347fde0240ba95977e1aadf6e94cf2151/src/index.ts#L280

**Comment by ClickSimply** [comment]
`1.1.2` is now live on NPM, this issue has been resolved.  Feel free to comment if you find anything further!
