### ISSUE TITLE
Memory-leak if we call `db.close()` right after `new SnapDB()` without `db.ready()`

### ISSUE THREAD

**Issue by huan** [ClickSimply/snap-db#5]
According to the fix of #2, I believe we also need to put some code inside the `close()` function.

The following code will demonstrate that the node program will hang.

```ts
#!/usr/bin/env ts-node

import {
  SnapDB,
}               from 'snap-db'

async function main () {
  const db = new SnapDB({
    dir: '/tmp/xx',
    key: 'string',
  })
  // await db.ready()
  await db.close()
  console.info('DB close-ed')
}

main()
```

If we uncomment the `await db.ready()` in the code, then everything will ok.

**Comment by ClickSimply** [comment]
`1.1.2` is now live on NPM, this issue has been resolved.  Feel free to comment if you find anything further!

**Comment by huan** [comment]
Thanks for the fix!
