### ISSUE TITLE
Could we setup a CI for this repo?

### ISSUE THREAD

**Issue by huan** [ClickSimply/snap-db#6]
It would be very convenient for the developer who sends Pull Requests to see the test result automatically.

And also, I'd like to suggest that we can publish the NPM module automatically by the CI (with the version bump automatically too). I do it in all [my NPM modules](https://www.npmjs.com/~zixia)

I'm very familiar with Travis CI, would love to add the config file for you if you want to.

**Comment by ClickSimply** [comment]
Thanks so much for your help with everything Huan!

I've never spent the time figuring out how to properly do a CI, would be awesome to have it setup to see how everything works!

Submit a PR and we'll get things going!

**Comment by huan** [comment]
We can expect the Travis CI work for this repository like [this](https://travis-ci.com/huan/snap-db/builds/123361004)

**Comment by ClickSimply** [comment]
`1.1.3` has been released on NPM and resolves this issue.  Feel free to comment if you find anything further!

**Comment by huan** [comment]
I think we need to enable the Travis CI for this repository after merge my PR so that it can take effect in the future commits.
