### ISSUE TITLE
Could we also add a `queryKeysIt()` method with the `QueryArgs` optoins?

### ISSUE THREAD

**Issue by huan** [ClickSimply/snap-db#9]
According to https://github.com/ClickSimply/snap-db/issues/1#issuecomment-521450992, I would like to have a `queryKeysIt()` so that I can get the `keys` by a `queryArgs`.

Currently, I have to get an iterator of both [key, value] and filter out the key. If we can have the `queryKeysIt` with a `queryArgs`, then I'll be able to filter out the keys I needed, and I guess that would be a huge improvement of the performance (because all the keys are in memory)?

**Comment by ClickSimply** [comment]
You can already do this with array destructuring.

```ts
const data = await db.queryIt({values: false});
for await (const [key, value] of data) {
    console.log(key);
}
```

**Comment by huan** [comment]
Fantastic!

Thanks for this awesome API. :smile:
